Parameters:
  Env:
    Type: String
    Default: local
    AllowedValues:
      - local
      - dev
      - prod
    Description: The environment.

Resources:
  DeploymentBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: 
        Fn::Join: [-, ['foodlose-deployment-bucket', !Ref Env]]

