AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Foodlose Serverless Application backend
Globals:
  Function:
    Runtime: python3.7
  Api:
    Name: FoodloseApi
    Cors:
      AllowHeaders: '''*'''
      AllowMethods: '''*'''
      AllowOrigin: '''*'''
Resources:
  MySNSTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: FoodloseContactMessage
  LoginFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://foodlose-deployment-bucket-dev/7153d8f9fa447b6e30b23d5eed05d7d6
      Handler: handler.auth.login.main
      Events:
        Login:
          Type: Api
          Properties:
            Path: /login
            Method: post
  CreateProfileFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://foodlose-deployment-bucket-dev/2ebb71b23114a9371088ac8db8159540
      Handler: handler.profile.create_profile.main
      Events:
        Login:
          Type: Api
          Properties:
            Path: /user
            Method: post
  DeleteProfileFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://foodlose-deployment-bucket-dev/16ad9eaa30c8aa13f4339cf766abdaf9
      Handler: handler.profile.delete_profile.main
      Events:
        Login:
          Type: Api
          Properties:
            Path: /user/{user_id}
            Method: delete
  UpdateProfileFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://foodlose-deployment-bucket-dev/148bc2de1c1671ce92a50198d2292892
      Handler: handler.profile.update_profile.main
      Events:
        Login:
          Type: Api
          Properties:
            Path: /user/{user_id}
            Method: put
  GetProfileFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://foodlose-deployment-bucket-dev/d9b3b90e9c9c5c7939c711785dac6e0c
      Handler: handler.profile.get_profile.main
      Events:
        Login:
          Type: Api
          Properties:
            Path: /user/{user_id}
            Method: get
  ListProfilesFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://foodlose-deployment-bucket-dev/c385cf3aa1ca0c5f8cad0c44e64d3159
      Handler: handler.profile.list_profiles.main
      Events:
        Login:
          Type: Api
          Properties:
            Path: /user
            Method: get
  CreateRecordFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://foodlose-deployment-bucket-dev/e286fd02e97684d03339ae12336331c2
      Handler: handler.profile.create_record.main
      Events:
        Login:
          Type: Api
          Properties:
            Path: /user/{user_id}/record
            Method: post
  DeleteRecordFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://foodlose-deployment-bucket-dev/ed410cff0753cfbb00e44039fe30dee6
      Handler: handler.profile.delete_record.main
      Events:
        Login:
          Type: Api
          Properties:
            Path: /user/{user_id}/record/{record_id}
            Method: delete
  GetRecordFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://foodlose-deployment-bucket-dev/065de9f3f5bdb4838ee6dde8c9df89d6
      Handler: handler.profile.get_record.main
      Events:
        Login:
          Type: Api
          Properties:
            Path: /user/{user_id}/record/{record_id}
            Method: get
  ListRecordsFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://foodlose-deployment-bucket-dev/ed05799f912a151e41db932c2f356de9
      Handler: handler.profile.list_records.main
      Events:
        Login:
          Type: Api
          Properties:
            Path: /user/{user_id}/record
            Method: get
  CreatePostFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://foodlose-deployment-bucket-dev/0480ccede6c7ae00cae04b18570c744a
      Handler: handler.post.create_post.main
      Events:
        Login:
          Type: Api
          Properties:
            Path: /post
            Method: post
  DeletePostFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://foodlose-deployment-bucket-dev/a886f80a99a59afdd4ba837e78afb107
      Handler: handler.post.delete_post.main
      Events:
        Login:
          Type: Api
          Properties:
            Path: /post/{post_id}
            Method: delete
  GetPostFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://foodlose-deployment-bucket-dev/c5e5fe5ba5c1bb301bbadb187489c1ff
      Handler: handler.post.get_post.main
      Events:
        Login:
          Type: Api
          Properties:
            Path: /post/{post_id}
            Method: get
  ListPostsFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://foodlose-deployment-bucket-dev/0cbdb987b4d75e1adc44b2b1c6c0791d
      Handler: handler.post.list_posts.main
      Events:
        Login:
          Type: Api
          Properties:
            Path: /post
            Method: get
  UpdatePostFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://foodlose-deployment-bucket-dev/8ef5fdc8867cda561e068a30382e3a06
      Handler: handler.post.update_post.main
      Events:
        Login:
          Type: Api
          Properties:
            Path: /post
            Method: put
  ContactFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://foodlose-deployment-bucket-dev/a743e3d664cff5aad2989911bd80497c
      Handler: handler.contact.contact.main
      Events:
        Login:
          Type: Api
          Properties:
            Path: /contact
            Method: post
Outputs:
  FoodloseApi:
    Description: 'API Gateway endpoint URL for Prod stage of Foodlose '
    Value:
      Fn::Sub: https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/v1/hello/
