version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "dev"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1w4dxl4gpo8wd"
s3_prefix = "dev"
region = "eu-west-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"

